# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: Martin "Enselic" Nordholts' blog

# Short description (goes below the title; it will also be used in the RSS feed)
description: Personal blog of Martin "Enselic" Nordholts.

# Your name, as you want it to appear underneath each post and in the footer
author: Martin Nordholts

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: https://setofskills.com

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty

plugins_dir: _plugins

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.md, build.js, node_modules]

defaults:
  -
    scope:
      path: ""
    values:
      nav: Blog # To make Blog button active when reading posts
      layout: "default"

sass:
  style: compressed
